### ISSUE TITLE
Missings Constants folder

### ISSUE THREAD

**Issue by larry-koutsavlis-spok** [stints/vid-conf#1]
Hi, 
I'd like to build your source but at runtime, getting this error

Failed to compile.

./src/components/room.js
Module not found: Can't resolve '../constants' in 'C:\_Dev\webrtc\vid-conf\src\components'

**Comment by sceendy** [comment]
That seems intentional as it would have the api key among other secret keys.
A template of that config file without the values would be helpful here, though - including some documentation of what kind of values are needed.

**Comment by stints** [comment]
I'll update the readme to explain what you'll need to run this.

**Comment by stints** [comment]
Readme has been updated.
